---
volumes:
  etc_pihole-unbound:
  etc_pihole_dnsmasq-unbound:

networks:
    edge:
      external: true

services:
  pihole:
    # dns:
    #   - 127.0.0.1
    container_name: pihole
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DOCKER_BUILDKIT: 0
    pull_policy: build
    hostname: ${HOSTNAME}
    #domainname: ${DOMAIN_NAME}
    ports:
      - "0.0.0.0:53:53/tcp"
      - "0.0.0.0:53:53/udp"
      - "${PIHOLE_WEBPORT:-80}:80/tcp"
    environment:
      - DOCKER_BUILDKIT=0
      - TZ=${TZ:-UTC}
      - FTLCONF_webserver_api_password=${WEBPASSWORD}
      - FTLCONF_webserver_interface_theme=${WEBTHEME:-default-dark}
      - FTLCONF_dns_upstreams=127.0.0.1#5335
      - FTLCONF_dns_dnssec="true"
      - FTLCONF_dns_listeningMode=all
      - FTLCONF_LOCAL_IPV4=${LOCAL_IP}
      - BLOCKLISTS_URL=https://v.firebog.net/hosts/lists.php?type=tick
      - REGEX_BLACKLIST_URL=https://raw.githubusercontent.com/mmotti/pihole-regex/master/regex.list
    volumes:
      - etc_pihole-unbound:/etc/pihole:rw
      - etc_pihole_dnsmasq-unbound:/etc/dnsmasq.d:rw
    networks: 
      - edge
    restart: unless-stopped


